language: node_js
node_js:
  - "10.15.3"

sudo: required

notifications:
  email:
    recipients:
      - benarvin93@outlook.com
    on_success: always
    on_failure: always

branches:
  only:
  - source

install:
- sudo apt-get install git-core
- npm install -g hexo-cli

script:
- rm -rf /node_modules/*
- npm install
- hexo clean
- hexo g

after_script:
- git config user.name "${U_NAME}"
- git config user.email "${U_EMAIL}"
# 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
- sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
- hexo deploy